from typing import List, TypedDict, Annotated
from langchain_core.messages import BaseMessage

class Task(TypedDict):
    id: str
    description: str
    status: str # "pending", "in-progress", "completed", "failed"

class FileDiff(TypedDict):
    file_path: str
    diff: str # Unified diff format or similar
    action: str # "create", "modify", "delete"

class ProjectState(TypedDict):
    # messages is a list of messages, we use operator.add to append
    messages: Annotated[List[BaseMessage], operator.add]
    spec_document: str          # The immutable "North Star"
    current_plan: List[Task]    # Generated by Architect
    code_diffs: List[FileDiff]  # Proposed changes by Builder
    security_vaccines: List[str]# Context injected by Scribe
    retry_count: int            # For HITL trigger
    build_status: str           # "clean", "vulnerable", "broken"
